spring.application.name=library

# Configurações de conexão com o banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/library_hexagonal
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA / Hibernate (Recomendado)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



